apiVersion: v1
kind: Service
metadata:
  name: geth-{{ .Values.geth.network }}-full
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: geth-{{ .Values.geth.network }}-full-0
  ports:
  - protocol: TCP
    name: peers-tcp
    port: 30303
    targetPort: 30303
    nodePort: 30303
  - protocol: UDP
    name: peers-udp
    port: 30303
    targetPort: 30303
    nodePort: 30303
