apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30300
  selector:
    app: grafana
