apiVersion: v1
kind: Service
metadata:
  name: lighthouse-{{ .Values.lighthouse.network }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: lighthouse-{{ .Values.lighthouse.network }}
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 39000
  - protocol: UDP
    port: 9000
    targetPort: 9000
    nodePort: 39000
