apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse-{{ .Values.lighthouse.network }}
spec:
  serviceName: lighthouse-{{ .Values.lighthouse.network }}
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-{{ .Values.lighthouse.network }}
  template:
    metadata:
      labels:
        app: lighthouse-{{ .Values.lighthouse.network }}
    spec:
      initContainers:
        - name: setup-validators
          image: {{.Values.lighthouse.image.repository }}:{{.Values.lighthouse.image.tag }}
          command: ['sh', '-c', "mkdir -p /root/.lighthouse/pyrmont; cp -r /root/pyrmont/validators /root/.lighthouse/pyrmont/validators"]
          volumeMounts:
            - name: lighthouse-data
              mountPath: "/root/.lighthouse"
      containers:
        - name: lighthouse-{{ .Values.lighthouse.network }}-beacon
          image: {{.Values.lighthouse.image.repository }}:{{.Values.lighthouse.image.tag }}
          args:
            [
              "lighthouse",
              "--network", "{{ .Values.lighthouse.network }}", "beacon",
              "--http", "--http-address", "0.0.0.0",
              "--metrics",
              "--disable-auto-discover",
            ]
          env:
          ports:
            - containerPort: 9000
              name: lighthousepeers
            - containerPort: 5052
              name: lighthousehttp
          volumeMounts:
            - name: lighthouse-data
              mountPath: "/root/.lighthouse"
          resources:
            limits:
              memory: 8000Mi
            requests:
              memory: 1000Mi
        - name: lighthouse-{{ .Values.lighthouse.network }}-validator
          image: {{.Values.lighthouse.image.repository }}:{{.Values.lighthouse.image.tag }}
          args:
            [
              "lighthouse", "vc",
              "--network", "{{ .Values.lighthouse.network }}",
              "--http",
              "--init-slashing-protection",
            ]
          env:
          ports:
            - containerPort: 5062
              name: lighthousehttp
          volumeMounts:
            - name: lighthouse-data
              mountPath: "/root/.lighthouse"
          resources:
            limits:
              memory: 8000Mi
            requests:
              memory: 1000Mi
  volumeClaimTemplates:
    - metadata:
        name: lighthouse-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 256Gi
