apiVersion: v1
kind: Service
metadata:
  name: lighthouse
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: lighthouse-{{ .Values.lighthouse.network }}-0
  ports:
  - protocol: TCP
    port: 5052
    name: http
    targetPort: 5052
  - protocol: TCP
    port: 5054
    name: metrics
    targetPort: 5054
