apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chown", "-R", "65534:6553", "/prometheus"]
          volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
        - name: prometheus-setup
          image: {{.Values.prometheus.image.repository }}:{{.Values.prometheus.image.tag }}
          command: ['sh', '-c', "mv -f /scrape-targets.json /prometheus/targets/scrape-targets.json"]
          volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
      containers:
        - image: {{.Values.prometheus.image.repository }}:{{.Values.prometheus.image.tag }}
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 200Mi
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 25Gi
