apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: {{.Values.prometheus.image.repository }}:{{.Values.prometheus.image.tag }}
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
            - mountPath: /prometheus/targets
              name: prometheus-claim1
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 200Mi
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 25Gi
    - metadata:
        name: prometheus-claim1
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 25Gi
